"""
Planner domain models.
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class PlanType(str, Enum):
    """
    Type of execution plan.
    """

    SINGLE = "single"
    WORKFLOW = "workflow"


class WorkflowStep(BaseModel):
    """
    Represents a single workflow step.
    """

    model_config = ConfigDict(extra="forbid")

    step_number: int = Field(
        ...,
        description="Execution order of the step.",
    )

    agent: str = Field(
        ...,
        description="Agent responsible for executing this step.",
    )

    action: str = Field(
        ...,
        description="Input or action for the selected agent.",
    )

    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Agent-specific parameters.",
    )


class ExecutionPlan(BaseModel):
    """
    Multi-step execution plan.
    """

    model_config = ConfigDict(extra="forbid")

    steps: list[WorkflowStep] = Field(
        default_factory=list,
        description="Ordered workflow steps.",
    )


class PlannerResponse(BaseModel):
    """
    Planner response returned by the Planner.
    """

    model_config = ConfigDict(extra="forbid")

    plan_type: PlanType = Field(
        ...,
        description="Single agent or multi-step workflow.",
    )

    execution_plan: ExecutionPlan = Field(
        ...,
        description="Execution plan generated by the planner.",
    )

    reasoning: str = Field(
        ...,
        description="Planner reasoning.",
    )