"""
Mock implementation of the LLM provider.

Used for:
- Local development
- Unit testing
- Offline execution
"""

from app.ai.llm.base_llm import BaseLLM
from app.ai.llm.models import LLMRequest, LLMResponse


class MockLLM(BaseLLM):
    """
    Mock implementation of a Large Language Model.

    This implementation is intended for development and testing
    without calling a real LLM provider.
    """

    def __init__(self, response: str | None = None):
        """
        Initialize the mock LLM.

        Args:
            response:
                Optional fixed response returned for every request.
                If not provided, the incoming prompt is echoed back.
        """
        self._response = response

    async def generate(
        self,
        request: LLMRequest,
    ) -> LLMResponse:
        """
        Generate a mock response.
        """

        content = (
            self._response
            if self._response is not None
            else (
                "This is a mock response generated by MockLLM.\n\n"
                f"Prompt received:\n{request.prompt}"
            )
        )

        return LLMResponse(
            content=content,
            model="mock-llm",
            finish_reason="STOP",
            prompt_tokens=0,
            completion_tokens=0,
            total_tokens=0,
        )

    async def health_check(self) -> bool:
        """
        Verify that the mock LLM is available.
        """

        return True