'=========================================================
' AI Theme
'=========================================================

!include common-styles.puml
!include colors.puml
!include metadata.puml
!include enterprise-theme.puml