'=========================================================
' C4 Container Theme
'=========================================================

!include ../lib/c4/C4_Container.puml

!include common-styles.puml

!include enterprise-theme.puml