'=========================================================
' Sequence Theme
'=========================================================

!include common-styles.puml
!include colors.puml
!include metadata.puml